# Generated by Django 5.1.6 on 2025-02-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_blog_roadmap_subject_resource"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
        migrations.DeleteModel(
            name="Roadmap",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="subject",
        ),
        migrations.AddField(
            model_name="resource",
            name="category",
            field=models.CharField(
                choices=[
                    ("Sheet", "SDE Sheet"),
                    ("Book", "Book"),
                    ("Video", "Video Lecture"),
                ],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
    ]
