# Generated by Django 5.1.6 on 2025-02-23 10:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_internshipresource_sdesheet_videolecture_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hackathon",
            name="benefits",
        ),
        migrations.RemoveField(
            model_name="hackathon",
            name="description",
        ),
        migrations.RemoveField(
            model_name="hackathon",
            name="eligibility",
        ),
        migrations.RemoveField(
            model_name="hackathon",
            name="year",
        ),
        migrations.AddField(
            model_name="hackathon",
            name="end_date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="hackathon",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="hackathon",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hackathon",
            name="start_date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
