# Generated by Django 5.1.6 on 2025-02-23 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_chatroom_chatmessage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
